version: '3'

tasks:
  tests:
    desc: Run tests
    cmds:
      - go test ./... --cover

  vet:
    desc: Start go vet
    cmds:
      - go vet

  lint:
    desc: Start lint project
    cmds:
      - golangci-lint run
