name: lint-and-test

on:
  push:
  pull_request:

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod download

      - name: Gofmt
        run: gofmt -l .

      - name: Linter
        uses: golangci/golangci-lint-action@v8

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Test
        working-directory: ./src
        run: go test -v ./...
