name: lint-and-test

on:
  push:
  pull_request:

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod download

      - name: Tidy
        run:
          - go mod tidy
          - git diff --exit-code go.mod go.sum

      - name: Gofmt
        run: test -z "$(gofmt -l .)"

      - name: Linter
        uses: golangci/golangci-lint-action@v8

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: go test -v -race ./...
