name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Tidy
        run:
          - go mod tidy
          - git diff --exit-code go.mod go.sum

      - name: Gofmt
        run: test -z "$(gofmt -l .)"

      - name: Linter
        uses: golangci/golangci-lint-action@v8

      - name: Test
        run: go test -v -race ./...

      - name: Go release
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
